name: nextflow-minimal
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core tools
  - nextflow
  - fastqc=0.12.1
  - coreutils=9.1
  - bc
  - STAR=2.7.11b
  - bedtools
  - multiqc=1.16.0
